version: '3.8'
services:
  couchbase:
    image: couchbase:community
    ports:
      - "8091:8091"
      - "8092:8092"
      - "11210:11210"
    environment:
      COUCHBASE_ADMINISTRATOR_USERNAME: "admin"
      COUCHBASE_ADMINISTRATOR_PASSWORD: "password"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
